### PR TITLE
Which is better

### PR DESCRIPTION
**Pull request by Rolenzo9194**
This or your one? Or shall we combine them and keep all?

### CODE REVIEW

**Comment by TheFieryFalcon** [comment]
Please make your properties list compatible with the sets of base monopoly (so, same prices, and the same layout as the normal board)

**Comment by Rolenzo9194** [comment]
Just a question, will we need that? We don't have much time and besides, all we need to do is convey how bad a world with racism could be and how much better a world with minimal institutional racism could be.

**Comment by TheFieryFalcon** [comment]
Yes, it doesn't take much time

**Comment by Rolenzo9194** [comment]
However, if your spaces are placeholders for the original Monopoly spaces, I can modify them.

**Comment by TheFieryFalcon** [comment]
My spaces aren't done yet, they only make up about 1/3rd of the board

**Comment by Rolenzo9194** [comment]
Okay I'll replace the board spaces on my code with the original Monopoly ones. This should take 5 minutes depending on WPM

**Comment by Rolenzo9194** [comment]
By the way they will be the ones that came with the copy of Monopoly I had at my disposal until I came to Australia

**Comment by Rolenzo9194** [comment]
Problem is how do we provide a comparison of a world with minimal institutional racism with a world with a lot of institutional racism through this?

**Comment by TheFieryFalcon** [comment]
The world with minimal institutional racism is just normal monopoly, and we've all played that before

**Comment by Rolenzo9194** [comment]
That makes sense, but what if the teacher hasn't played it before, which is a bit rare but what if that's the case?

**Comment by Rolenzo9194** [comment]
Also what if the teacher doesn't have the python app? Do we compile this into .exe

**Comment by TheFieryFalcon** [comment]
Yes, we compile it into exe, and we can state in our rationale that we expect the person playing this to have played normal monopoly before

**Comment by Rolenzo9194** [comment]
And there you have it:
import GameofInequality as main
def initialisecards():
    go = main.Card(main.CardType.Go, "GO", 1)
    okr = main.Card(main.CardType.PROPERTY, "Old Kent Road", 2, b=60, c=main.Set.BROWN)
    chest1 = main.Card(main.CardType.COMMUNITYCHEST, "Community Chest Card", 3)
    wchr = main.Card(main.CardType.PROPERTY, "Whitechapel Road", 4, b=60, c=main.Set.BROWN)
    itax = main.Card(main.CardType.TAX, "Income Tax", 5, b=200)
    kcs = main.Card(main.CardType.PROPERTY, "King's Cross Station", 6, b=200, c=main.Set.STATION)
    tai = main.Card(main.CardType.PROPERTY, "The Angel, Islington", 7, b=100, c=main.Set.LIGHTBLUE)
    chance1 = main.Card(main.CardType.CHANCE, "Chance Card", 8)
    er = main.Card(main.CardType.PROPERTY, "Euston Road", 9, b=100, c=main.Set.LIGHTBLUE)
    pvr = main.Card(main.CardType.PROPERTY, "Pentonville Road", 10, b=120, c=main.Set.BROWN)
    jail = main.Card(main.CardType.JAIL, "Jail", 11)
    pm = main.Card(main.CardType.PROPERTY, "Pall Mall", 12, b=140, c=main.Set.MAGENTA)
    ecomp = main.Card(main.CardType.Property, "Electric Company", 13, b=150, c=main.Set.COMPANY)
    wh = main.Card(main.CardType.PROPERTY, "Whitehall", 14, b=140, c=main.Set.MAGENTA)
    nta = main.Card(main.CardType.PROPERTY, "Northumb'nd Avenue", 15, b=160, c=main.Set.MAGENTA)
    mbs = main.Card(main.CardType.PROPERTY, "Marylebone Station", 16, b=200, c=main.Set.STATION)
    bs = main.Card(main.CardType.PROPERTY, "Bow Street", 17, b=180, c=main.Set.ORANGE)
    chest2 = main.Card(main.CardType.COMMUNITYCHEST, "Community Chest Card", 18)
    gms = main.Card(main.CardType.PROPERTY, "Great Marlborough Street", 19, b=180, c=main.Set.ORANGE)
    vs = main.Card(main.CardType.PROPERTY, "Vine Street", 20, b=200, c=main.Set.ORANGE)
    fp = main.Card(main.CardType.FREEPARKING, "Free Parking", 21)
    str = main.Card(main.CardType.PROPERTY, "Strand", 22, b=220, c=main.Set.RED)
    chance2 = main.Card(main.CardType.CHANCE, "Chance Card", 23)
    fs = main.Card(main.CardType.PROPERTY, "Fleet Street", 24, b=220, c=main.Set.RED)
    ts = main.Card(main.CardType.PROPERTY, "Trafalgar Square", 25, b=240, c=main.Set.RED)
    fss = main.Card(main.CardType.PROPERTY, "Fenchurch St. Station", 26, b=200, c=main.Set.STATION)
    ls = main.Card(main.CardType.PROPERTY, "Leicester Square", 27, b=260, c=main.Set.YELLOW)
    cos = main.Card(main.CardType.PROPERTY, "Coventry Street", 28, b=260, c=main.Set.YELLOW)
    water = main.Card(main.CardType.PROPERTY, "Water Works", 29, b=150, c=main.Set.COMPANY)
    picady = main.Card(main.CardType.PROPERTY, "Piccadilly", 30, b=280, c=main.Set.YELLOW)
    gotojail = main.Card(main.CardTYPE.GOTOJAIL, "GO TO JAIL", 31)
    rgs = main.Card(main.CardType.PROPERTY, "Regent Street", 32, b=300, c=main.Set.GREEN)
    oxst = main.Card(main.CardType.PROPERTY, "Oxford Street", 33, b=300, c=main.Set.GREEN)
    community3 = main.Card(main.CardType.COMMUNITYCHEST, "Community Chest Card", 34)
    bos = main.Card(main.CardType.PROPERTY, "Bond Street", 35, b=320, c=main.Set.GREEN)
    lsst = main.Card(main.CardType.PROPERTY, "Liverpool St. Station", 36, b=200, c=main.Set.STATION)
    chance3 = main.Card(main.CardType.CHANCE, "Chance Card", 37)
    pkln = main.Card(main.CardType.PROPERTY, "Park Lane", 38, b=350, c=main.Set.DARKBLUE)
    suptx = main.Card(main.CardType.TAX, "Super Tax", 39, b=100)
    mayfr = main.Card(main.CardType.PROPERTY, "Mayfair", 40, b=400, c=main.Set.DARKBLUE)

    board = [go, okr, chest1, wchr, itax, kcs, tai, chance1, er, pvr, jail, pm, ecomp, wh, nta, mbs, bs, chest2, gms, vs, fp, str, chance2, fs, ts, fss, ls, cos, water, picady, gotojail, rgs, oxst, community3, bos, lsst, chance3, pkln, suptx, mayfr]

**Comment by Rolenzo9194** [comment]
the lines after the def were meant to be indented by the way

**Comment by Rolenzo9194** [comment]
shall I post this in a separate pull request or leave it here

**Comment by Rolenzo9194** [comment]
also we could instead of adding "we expect the person to have played the original Monopoly" say "Monopoly is a very popular game, with many people who have played it before, so we have made a game."

**Pull request closed without merging**
