### PR TITLE
Added a new description which help relates directly to institutional …

### PR DESCRIPTION
**Pull request by Rolenzo9194**
We need to add the description you may find in the code for more marks, as currently, ours doesn't look like a game that advocates against institutional racism.
Please respond, these are the closing hours of submission and we need to get it in on time.
Of course, if you don't respond, I will have no choice but to compile the game into a .exe myself and submit it.

### CODE REVIEW

**Review by TheFieryFalcon — APPROVED** [review]
lgtm

**Comment by Rolenzo9194** [comment]
I haven't submitted the backup presentation just yet.

**Comment by Rolenzo9194** [comment]
Can you send me the .exe as a zip

**Comment by Rolenzo9194** [comment]
media fire just won't work

**Comment by Rolenzo9194** [comment]
it says the download is dangerous and has been blocked

**Pull request merged**
